version: '3.8'

services:
  server:
    build: server
    command: "flask run --host 0.0.0.0 --port 5000"
    volumes:
      - ./server:/server
      - ${SLIDES}:/data/slides
      - ${ANNOTS}:/data/annots
    environment:
      - FLASK_ENV=development
      - FLASK_APP=server.py
      - LD_LIBRARY_PATH=/usr/local/lib
    ports:
      - "${REACT_APP_FLASK_SERVER_PORT}:5000"

  app:
    build: app
    command: "npm start"
    volumes:
      - ./app:/app
      - node-modules:/app/node_modules
    ports:
      - "${REACT_APP_PORT}:3000"
    depends_on:
      - server

volumes:
  node-modules: